# Generated by Django 3.2.7 on 2021-10-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(blank=True, max_length=140)),
                ('comment_like', models.BooleanField(null=True)),
                ('comment_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_from', models.ManyToManyField(related_name='reply_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Synth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
                ('info', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('synth_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField(blank=True, max_length=140)),
                ('reply_like', models.BooleanField(null=True)),
                ('reply_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='main_app.comment')),
                ('reply_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='sfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfk', to='main_app.synth'),
        ),
    ]
