# Generated by Django 3.2.7 on 2021-10-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('synth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main_app.synths')),
            ],
        ),
    ]
