# Generated by Django 3.2.7 on 2021-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synth',
            name='img',
            field=models.URLField(default=None),
        ),
    ]
