# Generated by Django 3.2.7 on 2021-10-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synth',
            name='review',
        ),
        migrations.AddField(
            model_name='synth',
            name='review',
            field=models.ManyToManyField(to='main_app.Review'),
        ),
    ]
