# Generated by Django 3.2.7 on 2021-10-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
