# Generated by Django 3.2.7 on 2021-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_synth_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synth',
            name='img',
            field=models.URLField(default=None, null=True),
        ),
    ]
