# Generated by Django 3.2.7 on 2021-10-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_synth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_id', to='main_app.synth'),
        ),
    ]
