# Generated by Django 3.2.7 on 2021-10-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sid',
        ),
    ]
